/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_menu (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_modifier (void);
GtkWidget* create_windowrecherche (void);
