/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion_des_equipements (void)
{
  GtkWidget *Gestion_des_equipements;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *label6;
  GtkWidget *image25;
  GtkWidget *buttonsuivant;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *label22;
  GtkWidget *image9;
  GtkWidget *labelmenu;
  GtkWidget *fixed3;
  GtkWidget *entryid1;
  GtkWidget *buttonchercher;
  GtkWidget *image5;
  GtkWidget *label46;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview1;
  GtkWidget *comboboxtrie;
  GtkWidget *buttontrie;
  GtkWidget *image19;
  GtkWidget *buttonmodifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label19;
  GtkWidget *buttonprecedent;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label21;
  GtkWidget *buttonsuivant1;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *label20;
  GtkWidget *image7;
  GtkWidget *labelafficher;
  GtkWidget *fixed4;
  GtkWidget *entryid;
  GtkWidget *entrynom;
  GtkObject *spinbuttonj_adj;
  GtkWidget *spinbuttonj;
  GtkObject *spinbuttona_adj;
  GtkWidget *spinbuttona;
  GtkWidget *entrymarque;
  GtkObject *spinbuttonlo_adj;
  GtkWidget *spinbuttonlo;
  GtkObject *spinbuttonh_adj;
  GtkWidget *spinbuttonh;
  GtkObject *spinbuttonla_adj;
  GtkWidget *spinbuttonla;
  GtkObject *spinbuttonm_adj;
  GtkWidget *spinbuttonm;
  GtkObject *spinbuttonprix_adj;
  GtkWidget *spinbuttonprix;
  GtkWidget *labelse;
  GtkWidget *comboboxse;
  GtkWidget *labeldimension;
  GtkWidget *labelprix;
  GtkWidget *labelmarque;
  GtkWidget *label15;
  GtkWidget *labelid;
  GtkWidget *buttonajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label16;
  GtkWidget *buttonsuivant2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *label17;
  GtkWidget *image3;
  GtkWidget *buttonprecedent1;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label18;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *labelnom;
  GtkWidget *labeldate;
  GtkWidget *labelerreurnom_ajouter_GST_equipement;
  GtkWidget *labelerreurmarque_ajouter_GST_equipement;
  GtkWidget *labelsuccesajouter_GST_equipement;
  GtkWidget *labelerreurid1_ajouter_GST_equipement;
  GtkWidget *labelerreurid_ajouter_GST_equipement;
  GtkWidget *labelajouter;
  GtkWidget *fixed7;
  GtkWidget *entrynom1;
  GtkObject *spinbuttonj1_adj;
  GtkWidget *spinbuttonj1;
  GtkObject *spinbuttonm1_adj;
  GtkWidget *spinbuttonm1;
  GtkObject *spinbuttona1_adj;
  GtkWidget *spinbuttona1;
  GtkWidget *entrymarque1;
  GtkObject *spinbuttonlo1_adj;
  GtkWidget *spinbuttonlo1;
  GtkObject *spinbuttonh1_adj;
  GtkWidget *spinbuttonh1;
  GtkObject *spinbuttonla1_adj;
  GtkWidget *spinbuttonla1;
  GtkObject *spinbuttonprix1_adj;
  GtkWidget *spinbuttonprix1;
  GtkWidget *buttonprecedent2;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label37;
  GtkWidget *buttonsuivant3;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *label38;
  GtkWidget *image14;
  GtkWidget *buttonmodifier1;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image21;
  GtkWidget *label47;
  GtkWidget *treeview3;
  GtkWidget *labelse1;
  GtkWidget *labeletatpanne;
  GtkWidget *radiobuttonok;
  GSList *radiobuttonok_group = NULL;
  GtkWidget *radiobuttonen_panne;
  GtkWidget *labelnom1;
  GtkWidget *labelmarque1;
  GtkWidget *labeldate1;
  GtkWidget *labelprix1;
  GtkWidget *labeldimension1;
  GtkWidget *comboboxse1;
  GtkWidget *labelinfo3;
  GtkWidget *labelerreurnom_modifier_GST_equipement;
  GtkWidget *labelerrerumarque_modifier_GST_equipement;
  GtkWidget *labelErreur3;
  GtkWidget *labelmodifier;
  GtkWidget *fixed8;
  GtkObject *spinbuttontemps_darret_adj;
  GtkWidget *spinbuttontemps_darret;
  GtkWidget *labelTA;
  GtkObject *spinbuttoncout_dreparation_adj;
  GtkWidget *spinbuttoncout_dreparation;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview2;
  GtkWidget *buttontrie1;
  GtkWidget *image20;
  GtkWidget *comboboxtrie1;
  GtkWidget *buttonreparer;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image18;
  GtkWidget *label43;
  GtkWidget *buttonprecedent3;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image16;
  GtkWidget *label41;
  GtkWidget *buttonsuivant4;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *label42;
  GtkWidget *image17;
  GtkWidget *labelCR;
  GtkWidget *labelinforep;
  GtkWidget *labelreparer;
  GtkWidget *fixed6;
  GtkWidget *buttoncapt_T;
  GtkWidget *buttoncapt_H;
  GtkWidget *buttonprecedent4;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image22;
  GtkWidget *label51;
  GtkWidget *buttonexit;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *label52;
  GtkWidget *image24;
  GtkWidget *labelresultat;
  GtkWidget *label49;
  GtkWidget *label48;
  GtkWidget *label5;

  Gestion_des_equipements = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_equipements), _("Gestion des equipements"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Gestion_des_equipements), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1256, 672);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  label6 = gtk_label_new (_("<b><span color='red' size='17000'>Bienvenue dans l'interface du gestion des equipements !</span></b>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 272, 0);
  gtk_widget_set_size_request (label6, 760, 40);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  image25 = create_pixmap (Gestion_des_equipements, "SmartFarm.jpeg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed2), image25, 80, 40);
  gtk_widget_set_size_request (image25, 1096, 560);

  buttonsuivant = gtk_button_new ();
  gtk_widget_show (buttonsuivant);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonsuivant, 654, 544);
  gtk_widget_set_size_request (buttonsuivant, 96, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonsuivant), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  label22 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox7), label22, FALSE, FALSE, 0);

  image9 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  labelmenu = gtk_label_new (_("<b>MENU</b>"));
  gtk_widget_show (labelmenu);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), labelmenu);
  gtk_label_set_use_markup (GTK_LABEL (labelmenu), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entryid1 = gtk_entry_new ();
  gtk_widget_show (entryid1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryid1, 816, 32);
  gtk_widget_set_size_request (entryid1, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid1), 8226);

  buttonchercher = gtk_button_new ();
  gtk_widget_show (buttonchercher);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonchercher, 992, 32);
  gtk_widget_set_size_request (buttonchercher, 40, 32);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (buttonchercher), image5);

  label46 = gtk_label_new (_("<b><span color='blue'>Pour supprimer un equipement un double click le fera\nPour modifier un equipement il faut selement s\303\251lectionner une ligne puis appuyer sur la boutton modifier \nPour chercher un equipement il suffit d'ecrire son ID  i\303\247i =============================================></span></b>"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed3), label46, 0, 0);
  gtk_widget_set_size_request (label46, 816, 56);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow2, 0, 72);
  gtk_widget_set_size_request (scrolledwindow2, 1240, 400);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview1);
  gtk_widget_set_size_request (treeview1, 1040, 400);

  comboboxtrie = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxtrie);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxtrie, 1040, 32);
  gtk_widget_set_size_request (comboboxtrie, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtrie), _("Trie(A==>Z)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtrie), _("Trie par prix(croissant)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtrie), _("Trie par prix(decroissant)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtrie), _("Trie par marque"));

  buttontrie = gtk_button_new ();
  gtk_widget_show (buttontrie);
  gtk_fixed_put (GTK_FIXED (fixed3), buttontrie, 1208, 32);
  gtk_widget_set_size_request (buttontrie, 34, 32);

  image19 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (buttontrie), image19);

  buttonmodifier = gtk_button_new ();
  gtk_widget_show (buttonmodifier);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonmodifier, 550, 480);
  gtk_widget_set_size_request (buttonmodifier, 112, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonmodifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox4), label19, FALSE, FALSE, 0);

  buttonprecedent = gtk_button_new ();
  gtk_widget_show (buttonprecedent);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonprecedent, 455, 544);
  gtk_widget_set_size_request (buttonprecedent, 112, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonprecedent), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Precedent"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox6), label21, FALSE, FALSE, 0);

  buttonsuivant1 = gtk_button_new ();
  gtk_widget_show (buttonsuivant1);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonsuivant1, 645, 544);
  gtk_widget_set_size_request (buttonsuivant1, 112, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonsuivant1), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  label20 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox5), label20, FALSE, FALSE, 0);

  image7 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  labelafficher = gtk_label_new (_("<b>Afficher</b>"));
  gtk_widget_show (labelafficher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), labelafficher);
  gtk_label_set_use_markup (GTK_LABEL (labelafficher), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed4), entryid, 152, 44);
  gtk_widget_set_size_request (entryid, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed4), entrynom, 152, 144);
  gtk_widget_set_size_request (entrynom, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  spinbuttonj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonj_adj), 1, 0);
  gtk_widget_show (spinbuttonj);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonj, 152, 244);
  gtk_widget_set_size_request (spinbuttonj, 48, 27);

  spinbuttona_adj = gtk_adjustment_new (1, 1900, 2100, 1, 10, 10);
  spinbuttona = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttona_adj), 1, 0);
  gtk_widget_show (spinbuttona);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttona, 288, 244);
  gtk_widget_set_size_request (spinbuttona, 75, 27);

  entrymarque = gtk_entry_new ();
  gtk_widget_show (entrymarque);
  gtk_fixed_put (GTK_FIXED (fixed4), entrymarque, 152, 344);
  gtk_widget_set_size_request (entrymarque, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymarque), 8226);

  spinbuttonlo_adj = gtk_adjustment_new (4.05999994278, 0, 1000, 0.00999999977648, 10, 10);
  spinbuttonlo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonlo_adj), 1, 2);
  gtk_widget_show (spinbuttonlo);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonlo, 1056, 144);
  gtk_widget_set_size_request (spinbuttonlo, 64, 27);

  spinbuttonh_adj = gtk_adjustment_new (1.04999995232, 0, 1000, 0.00999999977648, 10, 10);
  spinbuttonh = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonh_adj), 1, 2);
  gtk_widget_show (spinbuttonh);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonh, 976, 144);
  gtk_widget_set_size_request (spinbuttonh, 64, 27);

  spinbuttonla_adj = gtk_adjustment_new (0.0599999986589, 0, 1000, 0.00999999977648, 10, 10);
  spinbuttonla = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonla_adj), 1, 2);
  gtk_widget_show (spinbuttonla);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonla, 880, 144);
  gtk_widget_set_size_request (spinbuttonla, 68, 27);

  spinbuttonm_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonm_adj), 1, 0);
  gtk_widget_show (spinbuttonm);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonm, 224, 244);
  gtk_widget_set_size_request (spinbuttonm, 48, 27);

  spinbuttonprix_adj = gtk_adjustment_new (0, 0, 100000, 0.00999999977648, 10, 10);
  spinbuttonprix = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonprix_adj), 1, 2);
  gtk_widget_show (spinbuttonprix);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonprix, 880, 240);
  gtk_widget_set_size_request (spinbuttonprix, 224, 32);

  labelse = gtk_label_new (_("Source D'Energie:"));
  gtk_widget_show (labelse);
  gtk_fixed_put (GTK_FIXED (fixed4), labelse, 733, 50);
  gtk_widget_set_size_request (labelse, 128, 16);

  comboboxse = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxse);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxse, 877, 40);
  gtk_widget_set_size_request (comboboxse, 224, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse), _("Electrique\t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse), _("Main-d'oeuvre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse), _("Travail d'Animal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse), _("Essence"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse), _("Gazole"));

  labeldimension = gtk_label_new (_("Dimension:"));
  gtk_widget_show (labeldimension);
  gtk_fixed_put (GTK_FIXED (fixed4), labeldimension, 744, 152);
  gtk_widget_set_size_request (labeldimension, 112, 16);

  labelprix = gtk_label_new (_("Prix(DT):"));
  gtk_widget_show (labelprix);
  gtk_fixed_put (GTK_FIXED (fixed4), labelprix, 776, 248);
  gtk_widget_set_size_request (labelprix, 56, 16);

  labelmarque = gtk_label_new (_("Marque:"));
  gtk_widget_show (labelmarque);
  gtk_fixed_put (GTK_FIXED (fixed4), labelmarque, 72, 350);
  gtk_widget_set_size_request (labelmarque, 80, 16);

  label15 = gtk_label_new (_("Etat:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 776, 356);
  gtk_widget_set_size_request (label15, 57, 16);

  labelid = gtk_label_new (_("ID:"));
  gtk_widget_show (labelid);
  gtk_fixed_put (GTK_FIXED (fixed4), labelid, 72, 50);
  gtk_widget_set_size_request (labelid, 48, 16);

  buttonajouter = gtk_button_new ();
  gtk_widget_show (buttonajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonajouter, 550, 480);
  gtk_widget_set_size_request (buttonajouter, 112, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox1), label16, FALSE, FALSE, 0);

  buttonsuivant2 = gtk_button_new ();
  gtk_widget_show (buttonsuivant2);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonsuivant2, 645, 544);
  gtk_widget_set_size_request (buttonsuivant2, 112, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonsuivant2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  label17 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox2), label17, FALSE, FALSE, 0);

  image3 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  buttonprecedent1 = gtk_button_new ();
  gtk_widget_show (buttonprecedent1);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonprecedent1, 455, 544);
  gtk_widget_set_size_request (buttonprecedent1, 112, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonprecedent1), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Precedent"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox3), label18, FALSE, FALSE, 0);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Nouveau"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton1, 872, 352);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Occasion"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton2, 1016, 352);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  labelnom = gtk_label_new (_("Nom:"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed4), labelnom, 72, 150);
  gtk_widget_set_size_request (labelnom, 56, 16);

  labeldate = gtk_label_new (_("Date de l'ajout:"));
  gtk_widget_show (labeldate);
  gtk_fixed_put (GTK_FIXED (fixed4), labeldate, 24, 240);
  gtk_widget_set_size_request (labeldate, 128, 30);

  labelerreurnom_ajouter_GST_equipement = gtk_label_new (_("<span color='red'>*veuillez saisir un nom</span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), labelerreurnom_ajouter_GST_equipement, 408, 152);
  gtk_widget_set_size_request (labelerreurnom_ajouter_GST_equipement, 208, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelerreurnom_ajouter_GST_equipement), TRUE);

  labelerreurmarque_ajouter_GST_equipement = gtk_label_new (_("<span color='red'>*veuillez saisir une marque</span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), labelerreurmarque_ajouter_GST_equipement, 400, 352);
  gtk_widget_set_size_request (labelerreurmarque_ajouter_GST_equipement, 256, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelerreurmarque_ajouter_GST_equipement), TRUE);

  labelsuccesajouter_GST_equipement = gtk_label_new (_("<span color='#130DD8'>Equipement ajouter avec succ\303\250s ! </span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), labelsuccesajouter_GST_equipement, 408, 432);
  gtk_widget_set_size_request (labelsuccesajouter_GST_equipement, 384, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelsuccesajouter_GST_equipement), TRUE);

  labelerreurid1_ajouter_GST_equipement = gtk_label_new (_("<span color='red'>*Un equipement existe d\303\251j\303\240 avec l'id que vous avez saisie</span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), labelerreurid1_ajouter_GST_equipement, 56, 80);
  gtk_widget_set_size_request (labelerreurid1_ajouter_GST_equipement, 408, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelerreurid1_ajouter_GST_equipement), TRUE);

  labelerreurid_ajouter_GST_equipement = gtk_label_new (_("<span color='red'>*veuillez saisir une id</span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), labelerreurid_ajouter_GST_equipement, 400, 40);
  gtk_widget_set_size_request (labelerreurid_ajouter_GST_equipement, 232, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelerreurid_ajouter_GST_equipement), TRUE);

  labelajouter = gtk_label_new (_("<b>Ajouter</b>"));
  gtk_widget_show (labelajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), labelajouter);
  gtk_label_set_use_markup (GTK_LABEL (labelajouter), TRUE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  entrynom1 = gtk_entry_new ();
  gtk_widget_show (entrynom1);
  gtk_fixed_put (GTK_FIXED (fixed7), entrynom1, 152, 144);
  gtk_widget_set_size_request (entrynom1, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom1), 8226);

  spinbuttonj1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonj1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonj1_adj), 1, 0);
  gtk_widget_show (spinbuttonj1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonj1, 152, 240);
  gtk_widget_set_size_request (spinbuttonj1, 48, 27);

  spinbuttonm1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonm1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonm1_adj), 1, 0);
  gtk_widget_show (spinbuttonm1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonm1, 216, 240);
  gtk_widget_set_size_request (spinbuttonm1, 48, 27);

  spinbuttona1_adj = gtk_adjustment_new (1, 1900, 2100, 1, 10, 10);
  spinbuttona1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttona1_adj), 1, 0);
  gtk_widget_show (spinbuttona1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttona1, 288, 240);
  gtk_widget_set_size_request (spinbuttona1, 75, 27);

  entrymarque1 = gtk_entry_new ();
  gtk_widget_show (entrymarque1);
  gtk_fixed_put (GTK_FIXED (fixed7), entrymarque1, 144, 336);
  gtk_widget_set_size_request (entrymarque1, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymarque1), 8226);

  spinbuttonlo1_adj = gtk_adjustment_new (4.05999994278, 0, 1000, 0.00999999977648, 10, 10);
  spinbuttonlo1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonlo1_adj), 1, 2);
  gtk_widget_show (spinbuttonlo1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonlo1, 888, 232);
  gtk_widget_set_size_request (spinbuttonlo1, 64, 27);

  spinbuttonh1_adj = gtk_adjustment_new (1.04999995232, 0, 1000, 0.00999999977648, 10, 10);
  spinbuttonh1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonh1_adj), 1, 2);
  gtk_widget_show (spinbuttonh1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonh1, 968, 232);
  gtk_widget_set_size_request (spinbuttonh1, 64, 27);

  spinbuttonla1_adj = gtk_adjustment_new (0.0599999986589, 0, 1000, 0.00999999977648, 10, 10);
  spinbuttonla1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonla1_adj), 1, 2);
  gtk_widget_show (spinbuttonla1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonla1, 1048, 232);
  gtk_widget_set_size_request (spinbuttonla1, 68, 27);

  spinbuttonprix1_adj = gtk_adjustment_new (0, 0, 100000, 0.00999999977648, 10, 10);
  spinbuttonprix1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonprix1_adj), 1, 2);
  gtk_widget_show (spinbuttonprix1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonprix1, 888, 328);
  gtk_widget_set_size_request (spinbuttonprix1, 224, 27);

  buttonprecedent2 = gtk_button_new ();
  gtk_widget_show (buttonprecedent2);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonprecedent2, 455, 544);
  gtk_widget_set_size_request (buttonprecedent2, 112, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonprecedent2), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Precedent"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox11), label37, FALSE, FALSE, 0);

  buttonsuivant3 = gtk_button_new ();
  gtk_widget_show (buttonsuivant3);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonsuivant3, 645, 544);
  gtk_widget_set_size_request (buttonsuivant3, 112, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonsuivant3), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  label38 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox12), label38, FALSE, FALSE, 0);

  image14 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  buttonmodifier1 = gtk_button_new ();
  gtk_widget_show (buttonmodifier1);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonmodifier1, 550, 480);
  gtk_widget_set_size_request (buttonmodifier1, 112, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonmodifier1), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox17), image21, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox17), label47, FALSE, FALSE, 0);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview3, 0, 32);
  gtk_widget_set_size_request (treeview3, 1248, 56);

  labelse1 = gtk_label_new (_("Source D'Energie:"));
  gtk_widget_show (labelse1);
  gtk_fixed_put (GTK_FIXED (fixed7), labelse1, 728, 152);
  gtk_widget_set_size_request (labelse1, 128, 16);

  labeletatpanne = gtk_label_new (_("Etat panne:"));
  gtk_widget_show (labeletatpanne);
  gtk_fixed_put (GTK_FIXED (fixed7), labeletatpanne, 408, 400);
  gtk_widget_set_size_request (labeletatpanne, 89, 40);

  radiobuttonok = gtk_radio_button_new_with_mnemonic (NULL, _("OK"));
  gtk_widget_show (radiobuttonok);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobuttonok, 520, 408);
  gtk_widget_set_size_request (radiobuttonok, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonok), radiobuttonok_group);
  radiobuttonok_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonok));

  radiobuttonen_panne = gtk_radio_button_new_with_mnemonic (NULL, _("EN PANNE"));
  gtk_widget_show (radiobuttonen_panne);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobuttonen_panne, 648, 408);
  gtk_widget_set_size_request (radiobuttonen_panne, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonen_panne), radiobuttonok_group);
  radiobuttonok_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonen_panne));

  labelnom1 = gtk_label_new (_("Nom:"));
  gtk_widget_show (labelnom1);
  gtk_fixed_put (GTK_FIXED (fixed7), labelnom1, 72, 150);
  gtk_widget_set_size_request (labelnom1, 56, 16);

  labelmarque1 = gtk_label_new (_("Marque:"));
  gtk_widget_show (labelmarque1);
  gtk_fixed_put (GTK_FIXED (fixed7), labelmarque1, 48, 344);
  gtk_widget_set_size_request (labelmarque1, 80, 16);

  labeldate1 = gtk_label_new (_("Date:"));
  gtk_widget_show (labeldate1);
  gtk_fixed_put (GTK_FIXED (fixed7), labeldate1, 64, 240);
  gtk_widget_set_size_request (labeldate1, 56, 24);

  labelprix1 = gtk_label_new (_("Prix(DT):"));
  gtk_widget_show (labelprix1);
  gtk_fixed_put (GTK_FIXED (fixed7), labelprix1, 776, 328);
  gtk_widget_set_size_request (labelprix1, 56, 24);

  labeldimension1 = gtk_label_new (_("Dimension:"));
  gtk_widget_show (labeldimension1);
  gtk_fixed_put (GTK_FIXED (fixed7), labeldimension1, 744, 232);
  gtk_widget_set_size_request (labeldimension1, 112, 24);

  comboboxse1 = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxse1);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxse1, 888, 144);
  gtk_widget_set_size_request (comboboxse1, 224, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse1), _("Electrique\t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse1), _("Main-d'oeuvre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse1), _("Travail d'Animal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse1), _("Essence"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxse1), _("Gazole"));

  labelinfo3 = gtk_label_new (_("<b><span color='blue' size='13000'>Ceci est le ligne que vous avez choisi pour le modifier</span></b>"));
  gtk_widget_show (labelinfo3);
  gtk_fixed_put (GTK_FIXED (fixed7), labelinfo3, 192, 0);
  gtk_widget_set_size_request (labelinfo3, 936, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelinfo3), TRUE);

  labelerreurnom_modifier_GST_equipement = gtk_label_new (_("<span color='red'>*veuillez saisir un nom</span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), labelerreurnom_modifier_GST_equipement, 399, 148);
  gtk_widget_set_size_request (labelerreurnom_modifier_GST_equipement, 177, 20);
  gtk_label_set_use_markup (GTK_LABEL (labelerreurnom_modifier_GST_equipement), TRUE);

  labelerrerumarque_modifier_GST_equipement = gtk_label_new (_("<span color='red'>*veuillez saisir une marque</span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), labelerrerumarque_modifier_GST_equipement, 368, 339);
  gtk_widget_set_size_request (labelerrerumarque_modifier_GST_equipement, 272, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelerrerumarque_modifier_GST_equipement), TRUE);

  labelErreur3 = gtk_label_new ("");
  gtk_widget_show (labelErreur3);
  gtk_fixed_put (GTK_FIXED (fixed7), labelErreur3, 232, 440);
  gtk_widget_set_size_request (labelErreur3, 760, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelErreur3), TRUE);

  labelmodifier = gtk_label_new (_("<b>Modifier</b>"));
  gtk_widget_show (labelmodifier);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), labelmodifier);
  gtk_label_set_use_markup (GTK_LABEL (labelmodifier), TRUE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  spinbuttontemps_darret_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  spinbuttontemps_darret = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttontemps_darret_adj), 1, 0);
  gtk_widget_show (spinbuttontemps_darret);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbuttontemps_darret, 344, 408);
  gtk_widget_set_size_request (spinbuttontemps_darret, 80, 27);

  labelTA = gtk_label_new (_("Temps d'arr\303\252t(en jours):"));
  gtk_widget_show (labelTA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelTA, 168, 408);
  gtk_widget_set_size_request (labelTA, 168, 24);

  spinbuttoncout_dreparation_adj = gtk_adjustment_new (1, 0, 100000, 0.00999999977648, 10, 10);
  spinbuttoncout_dreparation = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttoncout_dreparation_adj), 1, 2);
  gtk_widget_show (spinbuttoncout_dreparation);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbuttoncout_dreparation, 880, 408);
  gtk_widget_set_size_request (spinbuttoncout_dreparation, 120, 27);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed8), scrolledwindow1, 16, 56);
  gtk_widget_set_size_request (scrolledwindow1, 1224, 344);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview2);
  gtk_widget_set_size_request (treeview2, 1048, 336);

  buttontrie1 = gtk_button_new ();
  gtk_widget_show (buttontrie1);
  gtk_fixed_put (GTK_FIXED (fixed8), buttontrie1, 1208, 8);
  gtk_widget_set_size_request (buttontrie1, 34, 32);

  image20 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_container_add (GTK_CONTAINER (buttontrie1), image20);

  comboboxtrie1 = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxtrie1);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxtrie1, 1008, 8);
  gtk_widget_set_size_request (comboboxtrie1, 192, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtrie1), _("Trie(A==>Z)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtrie1), _("Trie par prix(croissant)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtrie1), _("Trie par prix(decroissant)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtrie1), _("Trie par marque"));

  buttonreparer = gtk_button_new ();
  gtk_widget_show (buttonreparer);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonreparer, 550, 480);
  gtk_widget_set_size_request (buttonreparer, 112, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonreparer), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image18 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox16), image18, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("R\303\251parer"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox16), label43, FALSE, FALSE, 0);

  buttonprecedent3 = gtk_button_new ();
  gtk_widget_show (buttonprecedent3);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonprecedent3, 455, 544);
  gtk_widget_set_size_request (buttonprecedent3, 112, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonprecedent3), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox14), image16, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Precedent"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox14), label41, FALSE, FALSE, 0);

  buttonsuivant4 = gtk_button_new ();
  gtk_widget_show (buttonsuivant4);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonsuivant4, 645, 544);
  gtk_widget_set_size_request (buttonsuivant4, 112, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonsuivant4), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  label42 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox15), label42, FALSE, FALSE, 0);

  image17 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  labelCR = gtk_label_new (_("C\303\264ut des r\303\251parations"));
  gtk_widget_show (labelCR);
  gtk_fixed_put (GTK_FIXED (fixed8), labelCR, 680, 408);
  gtk_widget_set_size_request (labelCR, 200, 24);

  labelinforep = gtk_label_new (_("<b><span color='blue' size='13000'>Pour r\303\251parer un equipement il suffit de s\303\251lectionne une ligne \net remplire les informations concernant cette r\303\251paration</span></b>"));
  gtk_widget_show (labelinforep);
  gtk_fixed_put (GTK_FIXED (fixed8), labelinforep, 80, 8);
  gtk_widget_set_size_request (labelinforep, 904, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelinforep), TRUE);

  labelreparer = gtk_label_new (_("<b>R\303\251parer</b>"));
  gtk_widget_show (labelreparer);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), labelreparer);
  gtk_label_set_use_markup (GTK_LABEL (labelreparer), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  buttoncapt_T = gtk_button_new_with_mnemonic (_("Statistique pour le capteur du temperature "));
  gtk_widget_show (buttoncapt_T);
  gtk_fixed_put (GTK_FIXED (fixed6), buttoncapt_T, 376, 200);
  gtk_widget_set_size_request (buttoncapt_T, 520, 40);

  buttoncapt_H = gtk_button_new_with_mnemonic (_("Statistique pour le capteur d'humidit\303\251"));
  gtk_widget_show (buttoncapt_H);
  gtk_fixed_put (GTK_FIXED (fixed6), buttoncapt_H, 376, 256);
  gtk_widget_set_size_request (buttoncapt_H, 520, 40);

  buttonprecedent4 = gtk_button_new ();
  gtk_widget_show (buttonprecedent4);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonprecedent4, 455, 544);
  gtk_widget_set_size_request (buttonprecedent4, 112, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonprecedent4), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox18), image22, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Precedent"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox18), label51, FALSE, FALSE, 0);

  buttonexit = gtk_button_new ();
  gtk_widget_show (buttonexit);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonexit, 645, 544);
  gtk_widget_set_size_request (buttonexit, 112, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonexit), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  label52 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox19), label52, FALSE, FALSE, 0);

  image24 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox19), image24, FALSE, FALSE, 0);

  labelresultat = gtk_label_new ("");
  gtk_widget_show (labelresultat);
  gtk_fixed_put (GTK_FIXED (fixed6), labelresultat, 288, 448);
  gtk_widget_set_size_request (labelresultat, 680, 56);

  label49 = gtk_label_new (_("<b><span size='14000' color='blue'>Resultat:</span></b>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed6), label49, 560, 400);
  gtk_widget_set_size_request (label49, 128, 40);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label48 = gtk_label_new (_("<u><b><span color='blue' size='17000'>Statistique</span></b></u>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed6), label48, 312, 56);
  gtk_widget_set_size_request (label48, 648, 40);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  label5 = gtk_label_new (_("<b>Statistique</b>"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label5);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  g_signal_connect ((gpointer) buttonsuivant, "clicked",
                    G_CALLBACK (on_buttonsuivant_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonchercher, "clicked",
                    G_CALLBACK (on_buttonchercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttontrie, "clicked",
                    G_CALLBACK (on_buttontrie_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier, "clicked",
                    G_CALLBACK (on_buttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedent, "clicked",
                    G_CALLBACK (on_buttonprecedent_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuivant1, "clicked",
                    G_CALLBACK (on_buttonsuivant1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajouter, "clicked",
                    G_CALLBACK (on_buttonajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuivant2, "clicked",
                    G_CALLBACK (on_buttonsuivant2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedent1, "clicked",
                    G_CALLBACK (on_buttonprecedent1_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedent2, "clicked",
                    G_CALLBACK (on_buttonprecedent2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuivant3, "clicked",
                    G_CALLBACK (on_buttonsuivant3_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier1, "clicked",
                    G_CALLBACK (on_buttonmodifier1_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonok, "toggled",
                    G_CALLBACK (on_radiobuttonok_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonen_panne, "toggled",
                    G_CALLBACK (on_radiobuttonen_panne_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttontrie1, "clicked",
                    G_CALLBACK (on_buttontrie1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonreparer, "clicked",
                    G_CALLBACK (on_buttonreparer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedent3, "clicked",
                    G_CALLBACK (on_buttonprecedent3_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuivant4, "clicked",
                    G_CALLBACK (on_buttonsuivant4_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoncapt_T, "clicked",
                    G_CALLBACK (on_buttoncapt_T_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoncapt_H, "clicked",
                    G_CALLBACK (on_buttoncapt_H_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedent4, "clicked",
                    G_CALLBACK (on_buttonprecedent4_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonexit, "clicked",
                    G_CALLBACK (on_buttonexit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_equipements, Gestion_des_equipements, "Gestion_des_equipements");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label6, "label6");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image25, "image25");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonsuivant, "buttonsuivant");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label22, "label22");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image9, "image9");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelmenu, "labelmenu");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, entryid1, "entryid1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonchercher, "buttonchercher");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image5, "image5");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label46, "label46");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, comboboxtrie, "comboboxtrie");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttontrie, "buttontrie");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image19, "image19");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonmodifier, "buttonmodifier");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image6, "image6");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label19, "label19");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonprecedent, "buttonprecedent");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image8, "image8");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label21, "label21");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonsuivant1, "buttonsuivant1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label20, "label20");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image7, "image7");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelafficher, "labelafficher");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonj, "spinbuttonj");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttona, "spinbuttona");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, entrymarque, "entrymarque");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonlo, "spinbuttonlo");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonh, "spinbuttonh");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonla, "spinbuttonla");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonm, "spinbuttonm");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonprix, "spinbuttonprix");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelse, "labelse");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, comboboxse, "comboboxse");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labeldimension, "labeldimension");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelprix, "labelprix");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelmarque, "labelmarque");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label15, "label15");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelid, "labelid");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonajouter, "buttonajouter");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image2, "image2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label16, "label16");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonsuivant2, "buttonsuivant2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label17, "label17");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image3, "image3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonprecedent1, "buttonprecedent1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image4, "image4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label18, "label18");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labeldate, "labeldate");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelerreurnom_ajouter_GST_equipement, "labelerreurnom_ajouter_GST_equipement");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelerreurmarque_ajouter_GST_equipement, "labelerreurmarque_ajouter_GST_equipement");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelsuccesajouter_GST_equipement, "labelsuccesajouter_GST_equipement");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelerreurid1_ajouter_GST_equipement, "labelerreurid1_ajouter_GST_equipement");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelerreurid_ajouter_GST_equipement, "labelerreurid_ajouter_GST_equipement");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelajouter, "labelajouter");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, entrynom1, "entrynom1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonj1, "spinbuttonj1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonm1, "spinbuttonm1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttona1, "spinbuttona1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, entrymarque1, "entrymarque1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonlo1, "spinbuttonlo1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonh1, "spinbuttonh1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonla1, "spinbuttonla1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttonprix1, "spinbuttonprix1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonprecedent2, "buttonprecedent2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image13, "image13");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label37, "label37");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonsuivant3, "buttonsuivant3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label38, "label38");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image14, "image14");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonmodifier1, "buttonmodifier1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image21, "image21");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label47, "label47");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelse1, "labelse1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labeletatpanne, "labeletatpanne");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, radiobuttonok, "radiobuttonok");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, radiobuttonen_panne, "radiobuttonen_panne");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelnom1, "labelnom1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelmarque1, "labelmarque1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labeldate1, "labeldate1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelprix1, "labelprix1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labeldimension1, "labeldimension1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, comboboxse1, "comboboxse1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelinfo3, "labelinfo3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelerreurnom_modifier_GST_equipement, "labelerreurnom_modifier_GST_equipement");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelerrerumarque_modifier_GST_equipement, "labelerrerumarque_modifier_GST_equipement");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelErreur3, "labelErreur3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelmodifier, "labelmodifier");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttontemps_darret, "spinbuttontemps_darret");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelTA, "labelTA");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, spinbuttoncout_dreparation, "spinbuttoncout_dreparation");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttontrie1, "buttontrie1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image20, "image20");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, comboboxtrie1, "comboboxtrie1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonreparer, "buttonreparer");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image18, "image18");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label43, "label43");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonprecedent3, "buttonprecedent3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image16, "image16");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label41, "label41");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonsuivant4, "buttonsuivant4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label42, "label42");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image17, "image17");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelCR, "labelCR");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelinforep, "labelinforep");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelreparer, "labelreparer");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttoncapt_T, "buttoncapt_T");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttoncapt_H, "buttoncapt_H");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonprecedent4, "buttonprecedent4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image22, "image22");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label51, "label51");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, buttonexit, "buttonexit");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label52, "label52");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, image24, "image24");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, labelresultat, "labelresultat");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label49, "label49");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label48, "label48");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements, label5, "label5");

  return Gestion_des_equipements;
}

