/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Gestion_des_equipements;
  GtkWidget *treeview1;
  GtkWidget *treeview2;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Gestion_des_equipements = create_Gestion_des_equipements ();
  gtk_widget_show (Gestion_des_equipements);
  treeview1=lookup_widget(Gestion_des_equipements,"treeview1");
  afficher_les_equipements(treeview1,"equipement.txt");
  treeview2=lookup_widget(Gestion_des_equipements,"treeview2");
  afficher_les_equipements(treeview2,"equipement_enpanne.txt");


  gtk_main ();
  return 0;
}

